version: 2
jobs:
  build:
    working_directory: ~/target-mobile  
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: Run linter
          command: npm run lint
